### ISSUE TITLE
Неправдоподобное движение поездов

### ISSUE THREAD

**Issue by staretc** [dyurgenson/MP_Project#2]
Одновременный проезд станций поездами на одном направлении (зависимость от предыдущего поезда, а не от интервала движения). Вследствие получается, что независимо, большой перегон или маленький между станциями, время переезда между ними одинаковое. [проблема не актуальна, если замысел движения поездов именно такой]

**Comment by dyurgenson** [comment]
Проблема одинакового времени переездов между станциями независимо от размера "перегона" возникает из-за схематичности карты метро и несоблюдения на ней реальных масштабов. Карта сделана схематично для удобства её использования
